[general]
# see https://github.com/alacritty/alacritty-theme?tab=readme-ov-file#color-schemes for available themes
import = ["themes/themes/catppuccin_mocha.toml"]
working_directory = "$HOME/Projects/"

[window]
startup_mode = "SimpleFullscreen"
blur = true
opacity = 0.69
padding = { x = 9, y = 3 }

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
size = 18.0
offset = { x = 1, y = 0 }
