[general]
# see https://github.com/alacritty/alacritty-theme?tab=readme-ov-file#color-schemes for available themes
import = [
    "themes/themes/catppuccin_mocha.toml",
    "alacritty.darwin.toml",
    "alacritty.linux.toml",
]

[window]
blur = true
opacity = 0.69
padding = { x = 9, y = 3 }

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
offset = { x = 1, y = 0 }
