#!/bin/sh
#
# File: .aliases
# Description:
#   contains all aliases defined by the user. Separated from shell rc files
#   for portability between different machines.
#   Avoid syntax and commands not portable to other different setups,
#   check out http://hyperpolyglot.org/unix-shells for more information

# checks if argument exists in path
exists() { command -p -v &>/dev/null }
is_zsh() { [ -n "$ZSH_VERSION" ] }
is_darwin() { [ $(uname) = Darwin ] }

# ls
# order of output:
# symbols, UPPERCASE, lowercase (folders first)
unalias ls 2>/dev/null
unfunction ls 2>/dev/null
alias l='LC_COLLATE=C ls -h --color=always --dereference-command-line-symlink-to-dir --group-directories-first'
alias ll='l -lF'
alias la='l -A'
alias lla='ll -AF'

# exa
alias ela='eza -F always -lah'
alias el='eza -F always -lh --group-directories-first'

# safe copy, move and delete
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'
if is_darwin; then
    unalias rm 2>/dev/null
    ! exists grm || alias rm='command grm -I'
fi

# backup a file
alias bakf='_f() { cp $1{,.bak.$(date +%s%N)} ; unset -f _f }; _f'

# safe chown
! is_darwin && {
  alias chown='chown --preserve-root'
  alias chmod='chmod --preserve-root'
  alias chgrp='chgrp --preserve-root'
}

# directories
unalias mkdir 2>/dev/null
alias md='mkdir -p'
alias rd='rmdir'
alias po='popd'
alias pu='pushd'

# create and move to a temp dir
alias cdtemp='cd $(mktemp -d)'

# hdd
is_darwin && alias df='df -h' || alias df='df -h -x squashfs'
alias du='du -h'

# summary of disk used by child items sorted and unsorted
alias dus='LANG=C du -s *'
alias duss='dus | LANG=C sort -h'
# disk space used by system folders
alias dusss="LANG=C du -s /{{boot,lib*,opt,sbin,tmp,usr,var}/*(N),{bin,etc,root}} 2>/dev/null | grep -vE '^(0|[0-9.]+K)' | LANG=C sort -h"

# shellcheck disable=SC2142
alias dskoff='_f(){ udisksctl power-off -b "$1"; unset -f _f }; _f'

alias diff='command diff -u --color'

# kill processes by partial name match
alias kp='_f(){ kill -9 $(ps aux | grep "$1" | grep -v grep | awk '"'"'{print $2}'"'"'); unset -f _f }; _f'

# sudo aliases
alias sudo='sudo '                      # expand aliases after sudo
alias usersu='sudo -E -s'               # preserve environment (-E option) when login as root
alias sudoit='sudo env PATH="$PATH" '   # preserve user PATH

## git
# NB! internal git aliases are in git/config

alias gap='git add -p'
alias gdw='git diff -w'
alias gds='git diff --staged'
alias gdsw='git diff --staged -w'

# git fetch
alias gf='git fetch --prune'
alias gfa='gf --all'

alias gpll='git pull'
alias gpsh='git push'

# git push
alias gpa='git push --all'
alias gpfa='git push --force-with-lease --all'
# prune remote branches
alias gpp='git push --prune --all'

# git pretty log
alias gl='git log --oneline --graph --decorate --color'
alias gla='git log --oneline --graph --decorate --color --all'
# Adds author and relative commit date
alias glg='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %Cblue<%an>%Creset" --abbrev-commit --date=relative'
alias glga='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %Cblue<%an>%Creset" --abbrev-commit --date=relative --all'

# git reset
alias grhs='git reset --soft'
alias 'grh!'="git reset --hard"
unalias grhh 2>/dev/null

## docker

# lazy-docker
alias lzd="docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/.lazydocker/config:/.config/jesseduffield/lazydocker lazyteam/lazydocker"

## python

alias python='python3'
alias pip='pip3'

# virtualenvwrapper
# strangely there is a 'workon' function, but no opposite
alias workoff='deactivate'

## utilities / apps

# open with system default application
alias o='open_command'
alias o.='o .'

# enable advanced calculation in bc by default
alias bc='bc -l'

# default parameters for youtube-dl
alias ytdl='youtube-dl --prefer-ffmpeg -o "%(title)s.%(ext)s"'

# terminating global aliases
is_zsh && {
    alias -g :L='| command less'
    alias -g :H='| command head'
    alias -g :T='| command tail'
    alias -g :G='| command grep'
    alias -g :LL='2>&1 | command less'
    alias -g :NE='2>/dev/null'
    alias -g :NO='1>/dev/null'
    alias -g :NUL='&>/dev/null'
}

## networking

# ip command
alias ip='ip -color'
alias ipb='ip -color -brief'

# list all LISTEN ports
alias listening='lsof -Pi | grep LISTEN'

# Visual Studio Code
alias vsc='code-insiders'
alias vsc.='code-insiders .'
alias ohmyzsh='vsc "$ZSH"'
alias zshrc='vsc "${ZDOTDIR:-$HOME}/.zshrc"'

# citrix-in-docker with KASM
alias citrix='docker run --dns 8.8.8.8 --rm -it --shm-size=512m -p 6901:6901 -e VNC_PW=password -e VNCOPTIONS="-publicIP 127.0.0.1" serpro69/kasm-citrix-workspace'

# last exit status
alias '?'='echo $?'

# hashicorp terraform
# NB! a lot of aliases for terraform come from 'terraform' zsh plugin
# Below are the ones that are missing (from my POV)
alias tfw='terraform workspace'

## gnu findutils
# https://www.gnu.org/software/findutils/

is_darwin && [ -d "/opt/homebrew/opt/findutils/bin" ] && {
  alias find=gfind
  # TODO: not sure if these should be aliased (i.e. usable at all on a mac)
  # alias locate=glocate
  # alias updatedb=gupdatedb
  alias xargs=gxargs
}

## clipboard
alias clipcat='_f(){ cat "$1" | xclip -selection clipboard; unset -f _f }; _f'
alias clippwd='_f(){ pwd | xclip -selection clipboard | trim; unset -f _f}; _f'

## misc

# nvim is installed via brew on mac and we can't use something similar to 'alternatives' like we have on Ubuntu to
# update global links and point vi(m) to nvim executable
is_darwin && {
  alias vi='nvim'
  alias vim='nvim'
}

# update nvim plugins
alias vimls='vim --headless "+Lazy! sync" +qa'
