#!/usr/bin/env bash

CONFIG_DEFAULT_USER="sergio"
CONFIG_CHARSET_UTF8=true
CONFIG_LANG="en_US"
#CONFIG_ZSH_PLUGINS="(zsh-vi-mode zsh-autosuggestions git git-extras gh gcloud kubectl gitignore z dircycle web-search sudo extract history-substring-search npm yarn github docker-compose sublime colorize colored-man-pages copybuffer dotenv grc fnm rust fast-syntax-highlighting git-prompt terraform)"
CONFIG_ZSH_PLUGINS="(colored-man-pages colorize copybuffer dircycle docker-compose dotenv extract fast-syntax-highlighting fnm gcloud gh git git-extras github gitignore git-prompt grc history-substring-search kubectl npm rust sublime sudo terraform web-search yarn z zsh-autosuggestions zsh-vi-mode spaceship-tfb-section spaceship-plb-section)"
CONFIG_ZSH_THEME="spaceship"
CONFIG_TERM_LOCAL="tmux" # terminal multiplexer: screen byobu tmux
CONFIG_TERM_SSH=""
