#!/usr/bin/env bash

# run google-cloud-cli via docker
gcloud-init () {
  if [ ! -d "$HOME/.config/gcloud" ]; then
    mkdir -p "$HOME/.config/gcloud"
  fi

  if [[ "$*" == *"--help"* ]]; then
    echo "Initialize gcloud to be used via docker"
    return 0
  fi
  docker run --rm -ti -u $(id -u):$(id -g) -v /etc/passwd:/etc/passwd -v $HOME/.config/gcloud:$HOME/.config/gcloud gcr.io/google.com/cloudsdktool/google-cloud-cli gcloud init
}

alias gcloud="docker run --rm -ti -u `id -u`:`id -g` -v /etc/passwd:/etc/passwd -v $HOME/.config/gcloud:$HOME/.config/gcloud -v $HOME/.kube:$HOME/.kube gcr.io/google.com/cloudsdktool/google-cloud-cli gcloud"

golangci-lint () {
  docker run --rm -v "$(pwd)":/app -w /app golangci/golangci-lint golangci-lint "$@"
}

mockery () {
  docker run --rm -v "$(pwd)":/src -w /src vektra/mockery "$@"
}
