---
name: Lint
run-name: ${{ github.actor }} is running Lint

on:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks:
    name: 🚰🔧 gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
